# dustybox-plugin-cddb/src/main/resources/plugin.yaml
name: "cd-database"
version: "1.3.0"
description: "Управление базой данных CD дисков"
mainClass: "com.dustymotors.plugins.cddb.CdDatabasePlugin"
springConfigClass: "com.dustymotors.plugins.cddb.CddbPluginConfig"
type: "database"